spring.application.name=centralpleingaz01

spring.datasource.url=jdbc:postgresql://${DB_HOST_LOCAL:${DB_HOST:localhost}}:${DB_PORT_LOCAL:${DB_PORT:5432}}/${DB_NAME:centralpleingaz}
spring.datasource.username=${DB_USER:pleingaz}
spring.datasource.password=${DB_PASS:pleingaz}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HBM2DDL:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI_LOCAL:http://localhost:8080/realms/PleinGazRealm}

server.address=0.0.0.0

server.port=8081